# Generated by Django 5.0.8 on 2026-02-22 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.supplierprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='supplieroffer',
            unique_together={('supplier', 'product')},
        ),
    ]
